---
apiVersion: v1
kind: Service
metadata:
  name: home-timeline-redis
  labels:
    death-star-project: social-network
    app: home-timeline-redis
  namespace: social-network
spec:
  ports:
  - port: 6379
  selector:
    death-star-project: social-network
    app: compose-post-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-timeline-redis
  labels:
    death-star-project: social-network
    app: home-timeline-redis
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: home-timeline-redis
  template:
    metadata:
      labels:
        death-star-project: social-network
        app: home-timeline-redis
      name: home-timeline-redis
    spec:
      containers:
      - name: home-timeline-redis
        image: redis:6.0.10
        imagePullPolicy: IfNotPresent
        args: ["/config/redis.conf"]
        volumeMounts:
        - mountPath: /config
          name: service-config
        - mountPath: /keys
          name: ssl-keys
      restartPolicy: Always
      volumes:
      - name: service-config
        configMap:
          name: service-config
      - name: ssl-keys
        configMap:
          name: ssl-keys
