---
apiVersion: v1
kind: Service
metadata:
  name: media-service
  labels:
    death-star-project: social-network
    app: media-service
  namespace: social-network
spec:
  ports:
  - port: 9090
  selector:
    death-star-project: social-network
    app: media-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-service
  labels:
    death-star-project: social-network
    app: media-service
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: media-service
  template:
    metadata:
      labels: 
        death-star-project: social-network
        app: media-service
      name: media-service
    spec:
      containers:
      - name: media-service
        image: social-network-microservices:latest
        imagePullPolicy: IfNotPresent
        command: ["MediaService"]
        volumeMounts:
          - mountPath: /social-network-microservices/config
            name: service-config
          - mountPath: /keys
            name: ssl-keys            
      restartPolicy: Always
      volumes:
        - name: service-config
          configMap:
            name: service-config
        - name: ssl-keys
          configMap:
            name: ssl-keys
