---
apiVersion: v1
kind: Service
metadata:
  name: social-graph-mongodb
  labels:
    death-star-project: social-network
    app: social-graph-mongodb
  namespace: social-network
spec:
  ports:
  - port: 27017
  selector:
    death-star-project: social-network
    app: social-graph-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-graph-mongodb
  labels:
    death-star-project: social-network
    app: social-graph-mongodb
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: social-graph-mongodb
  template:
    metadata:
      labels:
        death-star-project: social-network
        app: social-graph-mongodb
      name: social-graph-mongodb
    spec:
      containers:
      - name: social-graph-mongodb
        image: mongo:4.4.3
        imagePullPolicy: IfNotPresent
        args: ["--config", "/config/mongod.conf"]
        volumeMounts:
        - mountPath: /config
          name: service-config
        - mountPath: /keys
          name: ssl-keys
        - name: my-data
          mountPath: "/data/db"
      restartPolicy: Always
      volumes:
      - name: service-config
        configMap:
          name: service-config
      - name: ssl-keys
        configMap:
          name: ssl-keys
      - name: my-data
        emptyDir: {}
