apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: configmap-prometheus-conf
  namespace: hotel-res
data:
  alert.rules: |+
    groups:
    - name: node-alert
      rules:
      - alert: service_down
        expr: up == 0
        for: 2m
      - alert: high_load
        expr: node_load1 > 0.5
        for: 5m

  configure.yaml: |+
    global:
        scrape_interval: 5s
        external_labels:
            monitor: 'DSB-hotel-reservation'
    scrape_configs:
        - job_name: 'prometheus'
          static_configs:
              - targets: ['localhost:9090']
    #    - job_name: 'node-resources'
    #      scrape_interval: 10s
    #      static_configs:
    #          - targets: ['node-exporter:9100']
        - job_name: 'cadvisor'
          scrape_interval: 5s
          static_configs:
              - targets: ['cadvisor-out:8080']

    rule_files:
      - 'alert.rules'
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    death-star-project: hotel-res
    app: prometheus
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    death-star-project: hotel-res
    app: prometheus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    death-star-project: hotel-res
    app: prometheus
spec:
  selector:
    matchLabels:
      death-star-project: hotel-res
      app: prometheus
  template:
    metadata:
      labels:
        death-star-project: hotel-res
        app: prometheus
      name: prometheus
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.26.0
        args:
          - "--config.file=/usr/local/prometheus/configure.yaml"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: configure
          mountPath: /usr/local/prometheus/
          readOnly: true
        ports:
          - name: http
            containerPort: 9090
            protocol: TCP
      terminationGracePeriodSeconds: 30
      volumes:
      - name: configure
        configMap:
          name: configmap-prometheus-conf

