apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    death-star-project: hotel-res
    app-name: wrk-client
  namespace: hotel-res
  name: wrk-client
spec:
  replicas: {{.Values.frontend.count}}
  selector:
    matchLabels:
      death-star-project: hotel-res
      app-name: wrk-client
  strategy: {}
  template:
    metadata:
      name: wrk-client
      labels:
        death-star-project: hotel-res
        app-name: wrk-client
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: wrk-client
        command: ["sleep", "365d"]
        image: aenniwang/wrk-client
        imagePullPolicy: IfNotPresent
      restartPolicy: Always