version: "3"
services:
  config:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: social-network-microservices:latest
    hostname: config
    depends_on:
      - thrift-microservice-deps
    environment:
      - TLS
    entrypoint: [ "python3", "./scripts/config.py" ]
    volumes:
      - ./config:/social-network-microservices/config
      - ./nginx-web-server/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf

  thrift-microservice-deps:
    build:
      context: ./docker/thrift-microservice-deps
      dockerfile: ./cpp/Dockerfile
    image: thrift-microservice-social-deps:xenial

  social-graph-service:
    image: social-network-microservices:latest
    hostname: social-graph-service
    #    ports:
    #      - 10000:9090
    depends_on:
      config:
        condition: service_completed_successfully
      jaeger-agent:
        condition: service_started
      social-graph-mongodb:
        condition: service_started
    restart: always
    entrypoint: SocialGraphService
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  social-graph-mongodb:
    image: mongo:4.4.3
    hostname: social-graph-mongodb
    # ports:
    #   - 27018:27017
    depends_on:
      config:
        condition: service_completed_successfully
    restart: always
    command: --config /social-network-microservices/config/mongod.conf
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  social-graph-redis:
    image: redis:6.0.10
    hostname: social-graph-redis
    # ports:
    #   - 6380:6379
    depends_on:
      config:
        condition: service_completed_successfully
    restart: always
    command: /social-network-microservices/config/redis.conf
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  # write-home-timeline-service:
  #   image: social-network-microservices:latest
  #   hostname: write-home-timeline-service
  #   restart: always
  #   entrypoint: WriteHomeTimelineService
  #   depends_on:
  #     - write-home-timeline-rabbitmq

  # write-home-timeline-rabbitmq:
  #   image: rabbitmq
  #   hostname: write-home-timeline-rabbitmq
  #   environment:
  #     RABBITMQ_ERLANG_COOKIE: "WRITE-HOME-TIMELINE-RABBITMQ"
  #     RABBITMQ_DEFAULT_VHOST: "/"
  #   #    ports:
  #   #      - 15672:15672
  #   #      - 5672:5672
  #   restart: always

  home-timeline-redis:
    image: redis:6.0.10
    hostname: home-timeline-redis
    # ports:
    #   - 6381:6379
    depends_on:
      config:
        condition: service_completed_successfully
    restart: always
    command: /social-network-microservices/config/redis.conf
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  compose-post-service:
    image: social-network-microservices:latest
    hostname: compose-post-service
    #    ports:
    #      - 10001:9090
    restart: always
    depends_on:
      config:
        condition: service_completed_successfully
      jaeger-agent:
        condition: service_started
    entrypoint: ComposePostService
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  post-storage-service:
    image: social-network-microservices:latest
    hostname: post-storage-service
    ports:
      - 10002:9090
    restart: always
    depends_on:
      config:
        condition: service_completed_successfully
      jaeger-agent:
        condition: service_started
      post-storage-mongodb:
        condition: service_started
    entrypoint: PostStorageService
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  post-storage-memcached:
    image: memcached:1.6.8
    hostname: post-storage-memcached
    #    ports:
    #      - 11212:11211
    depends_on:
      config:
        condition: service_completed_successfully
    restart: always

  post-storage-mongodb:
    image: mongo:4.4.3
    hostname: post-storage-mongodb
    #    ports:
    #      - 27019:27017
    depends_on:
      config:
        condition: service_completed_successfully
    restart: always
    command: --config /social-network-microservices/config/mongod.conf
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  user-timeline-service:
    image: social-network-microservices:latest
    hostname: user-timeline-service
    #    ports:
    #      - 10003:9090
    restart: always
    depends_on:
      config:
        condition: service_completed_successfully
      jaeger-agent:
        condition: service_started
      user-timeline-mongodb:
        condition: service_started
    entrypoint: UserTimelineService
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  user-timeline-redis:
    image: redis:6.0.10
    hostname: user-timeline-redis
    #    ports:
    #      - 6383:6379
    depends_on:
      config:
        condition: service_completed_successfully
    restart: always
    command: /social-network-microservices/config/redis.conf
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  user-timeline-mongodb:
    image: mongo:4.4.3
    hostname: user-timeline-mongodb
    #    ports:
    #      - 27020:27017
    depends_on:
      config:
        condition: service_completed_successfully
    restart: always
    command: --config /social-network-microservices/config/mongod.conf
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  url-shorten-service:
    image: social-network-microservices:latest
    hostname: url-shorten-service
    #    ports:
    #      - 10004:9090
    restart: always
    entrypoint: UrlShortenService
    depends_on:
      config:
        condition: service_completed_successfully
      jaeger-agent:
        condition: service_started
      url-shorten-mongodb:
        condition: service_started
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  url-shorten-memcached:
    image: memcached:1.6.8
    hostname: url-shorten-memcached
    #    ports:
    #      - 11213:11211
    depends_on:
      config:
        condition: service_completed_successfully
    restart: always

  url-shorten-mongodb:
    image: mongo:4.4.3
    hostname: url-shorten-mongodb
    #    ports:
    #      - 27021:27017
    depends_on:
      config:
        condition: service_completed_successfully
    restart: always
    command: --config /social-network-microservices/config/mongod.conf
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  user-service:
    image: social-network-microservices:latest
    hostname: user-service
    #    ports:
    #      - 10005:9090
    restart: always
    depends_on:
      config:
        condition: service_completed_successfully
      jaeger-agent:
        condition: service_started
      user-mongodb:
        condition: service_started
    entrypoint: UserService
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  user-memcached:
    image: memcached:1.6.8
    hostname: user-memcached
    #    ports:
    #      - 11214:11211
    depends_on:
      config:
        condition: service_completed_successfully
    restart: always

  user-mongodb:
    image: mongo:4.4.3
    hostname: user-mongodb
    #    ports:
    #      - 27023:27017
    depends_on:
      config:
        condition: service_completed_successfully
    restart: always
    command: --config /social-network-microservices/config/mongod.conf
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  media-service:
    image: social-network-microservices:latest
    hostname: media-service
    #    ports:
    #      - 10006:9090
    depends_on:
      config:
        condition: service_completed_successfully
      jaeger-agent:
        condition: service_started
      media-mongodb:
        condition: service_started
    restart: always
    entrypoint: MediaService
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  media-memcached:
    image: memcached:1.6.8
    hostname: media-memcached
    #    ports:
    #      - 11215:11211
    depends_on:
      config:
        condition: service_completed_successfully
    restart: always

  media-mongodb:
    image: mongo:4.4.3
    hostname: media-mongodb
    #    ports:
    #      - 27024:27017
    depends_on:
      config:
        condition: service_completed_successfully
    restart: always
    command: --config /social-network-microservices/config/mongod.conf
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  text-service:
    image: social-network-microservices:latest
    hostname: text-service
    #    ports:
    #      - 10007:9090
    restart: always
    depends_on:
      config:
        condition: service_completed_successfully
      jaeger-agent:
        condition: service_started
    entrypoint: TextService
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  unique-id-service:
    image: social-network-microservices:latest
    hostname: unique-id-service
    #    ports:
    #      - 10008:9090
    restart: always
    depends_on:
      config:
        condition: service_completed_successfully
      jaeger-agent:
        condition: service_started
    entrypoint: UniqueIdService
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  user-mention-service:
    image: social-network-microservices:latest
    hostname: user-mention-service
    #    ports:
    #      - 10009:9090
    depends_on:
      config:
        condition: service_completed_successfully
      jaeger-agent:
        condition: service_started
    restart: always
    entrypoint: UserMentionService
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  home-timeline-service:
    image: social-network-microservices:latest
    hostname: home-timeline-service
    #    ports:
    #      - 10010:9090
    depends_on:
      config:
        condition: service_completed_successfully
      jaeger-agent:
        condition: service_started
    restart: always
    entrypoint: HomeTimelineService
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  nginx-thrift:
    build:
      context: ./docker/openresty-thrift
      dockerfile: ./xenial/Dockerfile
    image: openresty-thrift-social:xenial
    hostname: nginx-thrift
    ports:
      - 8080:8080
    depends_on:
      config:
        condition: service_completed_successfully
      jaeger-agent:
        condition: service_started
    restart: always
    volumes:
      - ./nginx-web-server/lua-scripts:/usr/local/openresty/nginx/lua-scripts
      - ./nginx-web-server/pages:/usr/local/openresty/nginx/pages
      - ./nginx-web-server/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx-web-server/jaeger-config.json:/usr/local/openresty/nginx/jaeger-config.json
      - ./gen-lua:/gen-lua
      - ./docker/openresty-thrift/lua-thrift:/usr/local/openresty/lualib/thrift
      - ./keys:/keys

  media-frontend:
    build:
      context: ./docker/media-frontend
      dockerfile: ./xenial/Dockerfile
    image: media-frontend:xenial
    hostname: media-frontend
    ports:
      - 8081:8080
    restart: always
    depends_on:
      config:
        condition: service_completed_successfully
      jaeger-agent:
        condition: service_started
    volumes:
      - ./media-frontend/lua-scripts:/usr/local/openresty/nginx/lua-scripts
      - ./media-frontend/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf

  jaeger-agent:
    image: jaegertracing/all-in-one:1.21.0
    hostname: jaeger-agent
    ports:
      #      - 5775:5775/udp
      #      - 6831:6831/udp
      #      - 6832:6832/udp
      #      - 5778:5778
      - 16686:16686
    #      - 14268:14268
    #      - 9411:9411
    restart: always
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
