apiVersion: v1
kind: Pod
metadata:
  name: wrk-client
  labels:
    death-star-project: media-microsvc
    app: wrk-client
  namespace: media-microsvc
spec:
  containers:
  - name: wrk-client
    image: aenniwang/wrk-client
    imagePullPolicy: IfNotPresent
    command: ["sleep", "360000"]

