---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    death-star-project: hotel-res
    app: prometheus
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    death-star-project: hotel-res
    app: prometheus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    death-star-project: hotel-res
    app: prometheus
spec:
  selector:
    matchLabels:
      death-star-project: hotel-res
      app: prometheus
  template:
    metadata:
      labels:
        death-star-project: hotel-res
        app: prometheus
      name: prometheus
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.26.0
        args:
          - "--config.file=/usr/local/prometheus/configure.yaml"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: configure
          mountPath: /usr/local/prometheus/
          readOnly: true
        ports:
          - name: http
            containerPort: 9090
            protocol: TCP
      terminationGracePeriodSeconds: 30
      volumes:
      - name: configure
        configMap:
          name: configmap-prometheus-conf

