---
apiVersion: v1
kind: Service
metadata:
  name: memcached-profile-{{ include "hotelres.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hotelres.labels" . | nindent 4 }}
    app-name: memcached-profile
spec:
  type: {{ include "hotelres.get" (list .Values "memcached-profile" "service.type") }}
  ports:
    - name: "memcached"
      port: 11211
      targetPort: 11211
  selector:
    {{- include "hotelres.selectorLabels" . | nindent 4 }}
    app-name: memcached-profile
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached-profile-{{ include "hotelres.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hotelres.labels" . | nindent 4 }}
    app-name: memcached-profile
spec:
  replicas: {{ include "hotelres.get" (list .Values "memcached-profile" "replicaCount") }}
  selector:
    matchLabels:
      {{- include "hotelres.selectorLabels" . | nindent 6 }}
      app-name: memcached-profile
  template:
    metadata:
      {{- with (include "hotelres.get" (list .Values "memcached-profile" "podAnnotations" "json") | mustFromJson) }}
      annotations:
        {{- toYaml . | nindent 8}}
      {{- end }}
      labels:
        {{- include "hotelres.selectorLabels" . | nindent 8 }}
        app-name: memcached-profile
    spec:
      {{- with (include "hotelres.get" (list .Values "memcached-profile" "imagePullSecrets" "json") | mustFromJson) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create -}}
      serviceAccountName: {{ include "hotelres.serviceAccountName" . }}
      {{- end }}
      {{- with (include "hotelres.get" (list .Values "memcached-profile" "podSecurityContext" "json") | mustFromJson) }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: memcached-profile
          {{- with (include "hotelres.get" (list .Values "memcached-profile" "securityContext" "json") | mustFromJson) }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "hotelres.get" (list .Values "memcached-profile" "image.repository") }}:{{ include "hotelres.get" (list .Values "memcached-profile" "image.tag") | default .Chart.AppVersion }}
          imagePullPolicy: {{ include "hotelres.get" (list .Values "memcached-profile" "image.pullPolicy") }}
          ports:
            - containerPort: 11211
          command:
            - "memcached"
            - "-c"
            - "65536"
          {{- with (include "hotelres.get" (list .Values "memcached-profile" "environments" "json") | mustFromJson) }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with (include "hotelres.get" (list .Values "memcached-profile" "resources" "json") | mustFromJson) }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with (include "hotelres.get" (list .Values "memcached-profile" "nodeSelector" "json") | mustFromJson) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (include "hotelres.get" (list .Values "memcached-profile" "affinity" "json") | mustFromJson) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (include "hotelres.get" (list .Values "memcached-profile" "tolerations" "json") | mustFromJson) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
