---
apiVersion: v1
kind: Service
metadata:
  name: profile-{{ include "hotelres.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hotelres.labels" . | nindent 4 }}
    app-name: profile
spec:
  type: {{ include "hotelres.get" (list .Values "profile" "service.type") }}
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    {{- include "hotelres.selectorLabels" . | nindent 4 }}
    app-name: profile

{{- if (include "hotelres.get" (list .Values "profile" "autoscaling.enabled" "json") | mustFromJson) }}
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: profile-{{ include "hotelres.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hotelres.labels" . | nindent 4 }}
    app-name: profile
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: profile-{{ include "hotelres.fullname" . }}
  minReplicas: {{ include "hotelres.get" (list .Values "profile" "autoscaling.minReplicas") }}
  maxReplicas: {{ include "hotelres.get" (list .Values "profile" "autoscaling.maxReplicas") }}
  metrics:
    {{- if (include "hotelres.get" (list .Values "profile" "autoscaling.targetCPUUtilizationPercentage" "json") | mustFromJson) }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ include "hotelres.get" (list .Values "profile" "autoscaling.targetCPUUtilizationPercentage") }}
    {{- end }}
    {{- if (include "hotelres.get" (list .Values "profile" "autoscaling.targetMemoryUtilizationPercentage" "json") | mustFromJson) }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ include "hotelres.get" (list .Values "profile" "autoscaling.targetMemoryUtilizationPercentage") }}
    {{- end }}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-{{ include "hotelres.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hotelres.labels" . | nindent 4 }}
    app-name: profile
spec:
  {{- if not (include "hotelres.get" (list .Values "profile" "autoscaling.enabled" "json") | mustFromJson) }}
  replicas: {{ include "hotelres.get" (list .Values "profile" "replicaCount") }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hotelres.selectorLabels" . | nindent 6 }}
      app-name: profile
  template:
    metadata:
      {{- with (include "hotelres.get" (list .Values "profile" "podAnnotations" "json") | mustFromJson) }}
      annotations:
        {{- toYaml . | nindent 8}}
      {{- end }}
      labels:
        {{- include "hotelres.selectorLabels" . | nindent 8 }}
        app-name: profile
    spec:
      {{- with (include "hotelres.get" (list .Values "profile" "imagePullSecrets" "json") | mustFromJson) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "hotelres.serviceAccountName" . }}
      {{- end }}
      {{- with (include "hotelres.get" (list .Values "profile" "podSecurityContext" "json") | mustFromJson) }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: profile
          {{- with (include "hotelres.get" (list .Values "profile" "securityContext" "json") | mustFromJson) }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "hotelres.get" (list .Values "profile" "image.repository") }}:{{ include "hotelres.get" (list .Values "profile" "image.tag") | default .Chart.AppVersion }}
          imagePullPolicy: {{ include "hotelres.get" (list .Values "profile" "image.pullPolicy") }}
          command:
            - profile
          ports:
            - containerPort: 8081
          env:
            - name: TLS
              value: {{ include "hotelres.get" (list .Values "profile" "features.tls") | quote }}
            - name: JAEGER_SAMPLE_RATIO
              value: {{ include "hotelres.get" (list .Values "profile" "features.jaegerSampleRatio") | quote }}
          {{- with (include "hotelres.get" (list .Values "profile" "environments" "json") | mustFromJson) }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with (include "hotelres.get" (list .Values "profile" "resources" "json") | mustFromJson) }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /go/src/github.com/harlow/go-micro-services/config.json
              subPath: config.json
              name: config-json
      volumes:
        - name: config-json
          configMap:
            name: configmap-{{ include "hotelres.fullname" . }}
            items:
            - key: config.json
              path: config.json
      {{- with (include "hotelres.get" (list .Values "profile" "nodeSelector" "json") | mustFromJson) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (include "hotelres.get" (list .Values "profile" "affinity" "json") | mustFromJson) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (include "hotelres.get" (list .Values "profile" "tolerations" "json") | mustFromJson) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
