{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hotelres.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hotelres.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.serviceAccount.rules }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "hotelres.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.serviceAccount.rules }}
rules:
  {{- toYaml . | nindent 2 }}
{{- end }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "hotelres.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "hotelres.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "hotelres.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
